package com.testmodule.util;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.Dialog;
import android.content.Intent;
import android.os.Bundle;
import android.view.WindowManager;

public class AttributionDialogActivity extends Activity {
    static final String KEY_MSG = "AttributionDialogActivity:msg";
    static final String DEFAULT_MSG = "Hello";


    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM);
        Intent intent = getIntent();
        String msg = DEFAULT_MSG;
        if (intent != null) {
            msg = intent.getStringExtra(KEY_MSG);
        }
        Dialog dialog = createDialog(msg);
        dialog.setOnDismissListener(dialog1 -> finish());
        dialog.show();
    }

    private Dialog createDialog(String msg) {
        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder
                .setMessage("The suggestions are generated by the InlineFillService. " + msg)
                .setNegativeButton(
                        "Settings",
                        (dialog, id) -> {
                            Intent intent = new Intent(this, SettingsActivity.class);
                            startActivity(intent);
                        })
                .setPositiveButton(
                        "Got it",
                        (dialog, id) -> {
                            // User cancelled the dialog
                        });
        return builder.create();
    }
}
